version: '3.8'

services:
  bot:
    build: .
    container_name: chto_by_prigotovit_bot
    restart: unless-stopped
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data  # Монтируем директорию для SQLite
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - ADMIN_IDS=${ADMIN_IDS}
      - PAYMENT_CARD_SBER=${PAYMENT_CARD_SBER}
      - PAYMENT_CARD_TINKOFF=${PAYMENT_CARD_TINKOFF}
      - PAYMENT_CARD_OWNER=${PAYMENT_CARD_OWNER}
    networks:
      - bot_network

# Удалите том db, если не используете PostgreSQL
# volumes:
#   db:

networks:
  bot_network:
    driver: bridge